CREATE TABLE MODULE
(
  GROUP_ID             VARCHAR2(150) NOT NULL ,
  MODULE_ID            VARCHAR2(150) NOT NULL ,
  MODULE_NAME          VARCHAR2(150) NOT NULL ,
  BROWSER_TITLE        VARCHAR2(255) NULL ,
  LAYOUT_ID            VARCHAR2(150) NULL ,
  SKIN                 VARCHAR2(250) NULL ,
  REG_DATE             DATE NULL
);

ALTER TABLE MODULE
  ADD CONSTRAINT  MODULE_PK PRIMARY KEY (MODULE_ID);

COMMENT ON TABLE MODULE IS '모듈';

COMMENT ON COLUMN MODULE.GROUP_ID IS '그룹ID';
COMMENT ON COLUMN MODULE.MODULE_ID IS '모듈ID';
COMMENT ON COLUMN MODULE.MODULE_NAME IS '모듈명';
COMMENT ON COLUMN MODULE.BROWSER_TITLE IS '브라우저 타이틀';
COMMENT ON COLUMN MODULE.LAYOUT_ID IS '레이아웃 ID';
COMMENT ON COLUMN MODULE.SKIN IS '스킨';
COMMENT ON COLUMN MODULE.REG_DATE IS '등록일';
