CREATE TABLE MODULE
(
  GROUP_ID             VARCHAR2(150) NOT NULL ,
	MODULE_ID            VARCHAR2(150) NOT NULL ,
	MODULE_NAME          VARCHAR2(150) NOT NULL ,
	BROWSER_TITLE        VARCHAR2(255) NULL ,
	SKIN                 VARCHAR2(250) NULL ,
	LAYOUT_ID            VARCHAR2(150) NULL ,
	REG_DATE             DATE NULL
);



ALTER TABLE MODULE
	ADD CONSTRAINT  MODULE_PK PRIMARY KEY (MODULE_IDX);



ALTER TABLE MODULE
ADD CONSTRAINT  MODULE_UQ_1 UNIQUE (MODULE_ID);



CREATE  INDEX MODULE_IDX_1 ON MODULE
(LAYOUT_IDX   ASC);