CREATE TABLE MODULE_OPTION
(
	NAME         VARCHAR2(150) NOT NULL ,
	VALUE        VARCHAR2(150) NULL ,
	MODULE_ID    VARCHAR2(150) NOT NULL
);

ALTER TABLE MODULE_OPTION
	ADD CONSTRAINT  MODULE_OPTION_PK PRIMARY KEY (MODULE_ID, NAME);

COMMENT ON TABLE MODULE_OPTION IS '모듈 옵션';

COMMENT ON COLUMN MODULE_OPTION.MODULE_ID IS '모듈ID';
COMMENT ON COLUMN MODULE_OPTION.NAME IS '옵션명';
COMMENT ON COLUMN MODULE_OPTION.VALUE IS '옵션값';