CREATE SEQUENCE PORTLET_IDX_SEQ;

CREATE TABLE PORTLET
(
	DASHBOARD_IDX     CHAR(20) NOT NULL ,
	PORTLET_IDX       CHAR(20) NOT NULL ,
	PORTLET_NAME      VARCHAR2(150) NOT NULL,
	PORTLET_ID        VARCHAR2(150) NOT NULL,
	WIDTH             NUMBER(2) NULL,
	HEIGHT            NUMBER(2) NULL,
	PADDING           NUMBER(2) NULL,
	COORD_X           NUMBER(2) NULL,
	COORD_Y           NUMBER(2) NULL,
	IS_STATIC         NUMBER(1) NULL,
	IS_DRAGGABLE      NUMBER(1) NULL,
	IS_RESIZABLE      NUMBER(1) NULL
);

ALTER TABLE PORTLET
	ADD CONSTRAINT  PORTLET_PK PRIMARY KEY (PORTLET_IDX);

COMMENT ON TABLE PORTLET IS '포틀릿';

COMMENT ON COLUMN PORTLET.DASHBOARD_IDX IS '대시보드번호';
COMMENT ON COLUMN PORTLET.PORTLET_IDX IS '포틀릿번호';
COMMENT ON COLUMN PORTLET.PORTLET_NAME IS '포틀릿명';
COMMENT ON COLUMN PORTLET.PORTLET_ID IS '포틀릿ID';
COMMENT ON COLUMN PORTLET.WIDTH IS '넓이';
COMMENT ON COLUMN PORTLET.HEIGHT IS '높이';
COMMENT ON COLUMN PORTLET.PADDING IS '여백';
COMMENT ON COLUMN PORTLET.COORD_X IS '위치X';
COMMENT ON COLUMN PORTLET.COORD_Y IS '위치Y';
COMMENT ON COLUMN PORTLET.IS_STATIC IS '동적여부';
COMMENT ON COLUMN PORTLET.IS_DRAGGABLE IS '드래그여부';
COMMENT ON COLUMN PORTLET.IS_RESIZABLE IS '리사이즈여부';